### ISSUE TITLE
what is the first thing to run this program locally?

### ISSUE THREAD

**Issue by Siddharth-Dhirde** [SiddharthDhirde/GreatCamp#9]
Please respond as soon as possible.
Thank you!

**Comment by SiddharthDhirde** [comment]
Hi!
first thing is that you need to install node js on your local system and then download this repo as zip. Further extract that zip folder and open it vs code. Now open new terminal in VS Code then run  `npm install`. This will install the necessary package. Then again in terminal   run this command: `npm start`. Hope this will help. If you face any further issue then let me know.

**Comment by Siddharth-Dhirde** [comment]
Thank you for helping out.
